jobs:
  build-linux-x64:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v3"
      with:
        submodules: true
    - uses: "actions/setup-dotnet@v2"
      with:
        global-json-file: "global.json"
    - run: "sudo apt-get install -y cmake ninja-build"
    - run: "dotnet restore"
    - run: "dotnet build ./src/Nsharp.Ninja.runtime.linux-x64/Nsharp.Ninja.runtime.linux-x64.csproj --configuration Release"
    - run: "dotnet pack ./src/Nsharp.Ninja.runtime.linux-x64/Nsharp.Ninja.runtime.linux-x64.csproj --configuration Release"
    - uses: "actions/upload-artifact@v3"
      with:
        name: "Nsharp.Ninja"
        path: "./src/Nsharp.Ninja.runtime.linux-x64/bin/Release/Nsharp.Ninja.runtime.linux-x64.*.nupkg"
  build-win-x64:
    runs-on: "windows-2022"
    steps:
    - uses: "actions/checkout@v3"
      with:
        submodules: true
    - uses: "actions/setup-dotnet@v2"
      with:
        global-json-file: "global.json"
    - run: "dotnet restore"
    - run: "dotnet build ./src/Nsharp.Ninja.runtime.win-x64/Nsharp.Ninja.runtime.win-x64.csproj --configuration Release"
    - run: "dotnet pack ./src/Nsharp.Ninja.runtime.win-x64/Nsharp.Ninja.runtime.win-x64.csproj --configuration Release"
    - uses: "actions/upload-artifact@v3"
      with:
        name: "Nsharp.Ninja"
        path: "./src/Nsharp.Ninja.runtime.win-x64/bin/Release/Nsharp.Ninja.runtime.win-x64.*.nupkg"
on: "push"
